Shivdev-- Added a portfolio
Evavic44/portfolio-ideas pull request #378
Opened 2023-12-16 14:35 UTC by ShivaniYadav07

### Portfolio Author

Shivani Yadav    (104)

### Portfolio Link?

https://shivaniyadav.online/

### GitHub Link:

https://github.com/ShivaniYadav07/

2023-12-16 15:21 UTC, israelmitolu requested changes
Hi @ShivaniYadav07 
The image is a bit large (520kb)
Kindly compress it using the [compressnow](https://compressnow.com/) or [tinypng](https://tinypng.com/), and upload it.

Thanks!

2023-12-17 05:57 UTC, ShivaniYadav07 commented
Done ! check it out

2023-12-17 23:19 UTC, Evavic44 approved these changes

2023-12-19 06:11 UTC, israelmitolu approved these changes
Awesome LGTM 💯

2023-12-19 06:11 UTC, merged