Added my portfolio details at README.md
Evavic44/portfolio-ideas pull request #433
Opened 2024-05-30 19:33 UTC by Moinak-Majumdar

### Portfolio Author

Moinak Majumdar

### Portfolio Link?

https://moinak05.vercel.app

### GitHub Link:

https://github.com/Moinak-Majumdar/portfolio

### Tech Stack

Next.js, TypeScript, Framer Motion, TailwindCss

2024-05-30 22:32 UTC, Evavic44 requested changes
Hey @Moinak-Majumdar thanks for adding your portfolio to the list. Can you kindly compress the screenshot using [Squoosh](https://squoosh.app)? Thanks

2024-05-31 05:43 UTC, Moinak-Majumdar commented
Thanks for informing me @Evavic44, I have updated the screenshot with the compress one at [commit](https://github.com/Evavic44/portfolio-ideas/pull/433/commits/4f0797a0575482f410b1b4f0c1849dbbc07f82fd).

2024-05-31 05:47 UTC, Moinak-Majumdar reviewed
Thanks for informing me **@Evavic44** , I have updated the screenshot with the compress one at [commit](https://github.com/Evavic44/portfolio-ideas/pull/433/commits/4f0797a0575482f410b1b4f0c1849dbbc07f82fd).

2024-05-31 07:10 UTC, Evavic44 approved these changes

2024-05-31 07:10 UTC, merged