Add Shivaraj's portfolio
Evavic44/portfolio-ideas pull request #454
Opened 2024-06-27 06:30 UTC by Shivaraj-Kolekar

### Portfolio Author
@Shivaraj-Kolekar

### Portfolio Link?
https://shivaraj-portfolio.vercel.app/

### GitHub Link:
https://github.com/Shivaraj-Kolekar/portfolio

### Tech Stack
HTML, TailwindCSS, Javascript

2024-06-27 06:58 UTC, israelmitolu requested changes
Hi @Shivaraj-Kolekar 
Kindly move your portfolio to the bottom of the list.

Thanks.

2024-06-29 08:46 UTC, Shivaraj-Kolekar commented
Hi @israelmitolu 
I have made the requested changes

2024-06-29 09:00 UTC, israelmitolu approved these changes
Great. Thanks @Shivaraj-Kolekar :)

2024-06-29 09:01 UTC, israelmitolu approved these changes

2024-06-29 09:01 UTC, merged